/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;

/**
 *
 * @author DanishJahangir
 */
public class addUser extends javax.swing.JFrame {

    /**
     * Creates new form addUser
     */
    public addUser() {
        initComponents();
        this.setLayout(new BorderLayout());
        // create the status bar panel and shove it down the bottom of the frame
        
        statusPanel.setBorder(new BevelBorder(BevelBorder.LOWERED));
        this.add(statusPanel, BorderLayout.SOUTH);
        statusPanel.setPreferredSize(new Dimension(this.getWidth(), 24));
        statusPanel.setLayout(new BoxLayout(statusPanel, BoxLayout.X_AXIS));
        
        statusLabel.setHorizontalAlignment(SwingConstants.LEFT);
        statusPanel.add(statusLabel);
        this.setVisible(true);
        
        //sets the icon image on the frame.
        this.setIconImage(new ImageIcon(getClass().getResource("ems.png")).getImage());        
    }
        JPanel statusPanel = new JPanel();
        JLabel statusLabel = new JLabel("Ready");
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_pwd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_vpwd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_accessLevel = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        lbl_pass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(":: ADD USER ::");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("UserName");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 70, 20);
        getContentPane().add(txt_username);
        txt_username.setBounds(131, 56, 150, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 60, 30);
        getContentPane().add(txt_pwd);
        txt_pwd.setBounds(130, 100, 154, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Verify");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 80, 30);

        txt_vpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_vpwdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_vpwdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_vpwdKeyTyped(evt);
            }
        });
        getContentPane().add(txt_vpwd);
        txt_vpwd.setBounds(130, 140, 154, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Access Level");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 65, 30);

        cb_accessLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "accountant", "user" }));
        getContentPane().add(cb_accessLevel);
        cb_accessLevel.setBounds(130, 180, 154, 30);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 220, 100, 30);

        lbl_pass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_pass);
        lbl_pass.setBounds(290, 140, 30, 30);

        setSize(new java.awt.Dimension(343, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnectSQLite i = new ConnectSQLite();
        
        String username = txt_username.getText();
        String password = txt_pwd.getText();
        String vpassword = txt_vpwd.getText();
        String a_lvl = cb_accessLevel.getSelectedItem().toString();
        if(a_lvl.equals("admin")){
            statusLabel.setForeground(Color.red);
            statusLabel.setText("Admin account can't be modified.");
            statusPanel.add(statusLabel);
        }else if(!(password.equals(vpassword))){
            statusLabel.setForeground(Color.red);
            statusLabel.setText("Password didn't match.");
            statusPanel.add(statusLabel);
        }else if(password.equals(vpassword) ){
            i.InsertData("Insert into tbl_users(e_user,e_pwd,e_alvl) values('"+username +"','" +password +"','" +a_lvl +"')");
            statusLabel.setForeground(Color.green);
            statusLabel.setText("Succesfully Created a new user");
            statusPanel.add(statusLabel);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_vpwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vpwdKeyPressed

    }//GEN-LAST:event_txt_vpwdKeyPressed

    private void txt_vpwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vpwdKeyTyped

    }//GEN-LAST:event_txt_vpwdKeyTyped

    private void txt_vpwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vpwdKeyReleased
        String password = txt_pwd.getText();
        if(txt_vpwd.getText().equals(password))
        {
            lbl_pass.setForeground(Color.green);
            lbl_pass.setText("OK");
        } else {
            lbl_pass.setForeground(Color.red);
            lbl_pass.setText("X");
        }
    }//GEN-LAST:event_txt_vpwdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//        }
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_accessLevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JTextField txt_pwd;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_vpwd;
    // End of variables declaration//GEN-END:variables
}
