package AppPackage;


import java.io.Console;
import java.lang.reflect.Method;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.DefaultEditorKit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DanishJahangir
 */
public class calcMain extends javax.swing.JFrame {

    /**
     * Creates new form calcMain
     */
    public calcMain() {
        initComponents();
        
        Library_File a = new Library_File();
        a.setStatusBar(statusPanel, statusLabel, this, "ems.png");
    }
    
    JPanel statusPanel = new JPanel();
    JLabel statusLabel = new JLabel("Ready");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_divide = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_mul = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_minus = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_equals = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASTO X9301 PRO");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(51, 51, 51));
        setName("calcMain"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        textField.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        textField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textField.setText("0");
        textField.setEnabled(false);
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
        });
        getContentPane().add(textField);
        textField.setBounds(10, 55, 285, 60);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel1.setText("CASTO X9301 PRO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 14, 166, 23);

        btn_7.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_7);
        btn_7.setBounds(10, 174, 60, 42);

        btn_8.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_8);
        btn_8.setBounds(76, 174, 60, 42);

        btn_9.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_9);
        btn_9.setBounds(142, 174, 60, 42);

        btn_divide.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_divide.setText("/");
        btn_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divideActionPerformed(evt);
            }
        });
        getContentPane().add(btn_divide);
        btn_divide.setBounds(208, 174, 87, 42);

        btn_4.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_4);
        btn_4.setBounds(10, 222, 60, 42);

        btn_5.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_5);
        btn_5.setBounds(76, 222, 60, 42);

        btn_mul.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_mul.setText("*");
        btn_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mul);
        btn_mul.setBounds(208, 222, 87, 42);

        btn_6.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_6);
        btn_6.setBounds(142, 222, 60, 42);

        btn_2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_2);
        btn_2.setBounds(76, 270, 60, 42);

        btn_minus.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_minus.setText("-");
        btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_minus);
        btn_minus.setBounds(208, 270, 87, 42);

        btn_1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_1);
        btn_1.setBounds(10, 270, 60, 42);

        btn_3.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_3);
        btn_3.setBounds(142, 270, 60, 42);

        btn_dot.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_dot.setText(".");
        getContentPane().add(btn_dot);
        btn_dot.setBounds(10, 318, 60, 42);

        btn_equals.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_equals.setText("=");
        btn_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_equals);
        btn_equals.setBounds(142, 318, 60, 42);

        btn_0.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_0);
        btn_0.setBounds(76, 318, 60, 42);

        btn_add.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add);
        btn_add.setBounds(208, 318, 87, 42);

        jButton17.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jButton17.setText("ON/OFF");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(155, 126, 140, 42);

        btn_remove.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        btn_remove.setText("REMOVE");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_remove);
        btn_remove.setBounds(10, 126, 140, 42);

        setSize(new java.awt.Dimension(321, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int one = 1;
    private int two = 2;
    private int three = 3;
    private int four = 4;
    private int five = 5;
    private int six = 6;
    private int seven = 7;
    private int eight = 8;
    private int nine = 9;
    private int zero = 0;
    private char dot = '.';
    private int val1 = 0;
    private int val2 = 0;
    private int resultant = 0;
    private boolean newField = false;
    private boolean waitForNew = false;
    
    
    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        keyEvent(textField, getSix());
    }//GEN-LAST:event_btn_6ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if(!(textField.getText().equals("")))
        {
            getTextField().setText("");
            setResultant(0);
            setVal1(0);
        }
        else
        {
            getTextField().setText("0");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    
    
    public void keyEvent(JTextField textField , int m)
    {
        if(isNewField())
        {
            textField.setText("" +m);
            setNewField(false);
        }else if(this.textField.getText().equals("0"))
        {
            this.textField.setText("" +m);
        }
        else if(this.textField.getText().length() >= 8)
        {
            //have to set a beep here
        }
        else
        {
            int display = Integer.parseInt(this.textField.getText());
            this.textField.setText("" +display +m);
        }
    }
    
    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        keyEvent(textField, getOne());
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        keyEvent(textField, getTwo());
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        keyEvent(textField, getThree());
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        keyEvent(textField, getFour());
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        keyEvent(textField, getFive());
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        keyEvent(textField, getSeven());
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        keyEvent(textField, getEight());
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        keyEvent(textField, getNine());
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        keyEvent(textField, getZero());
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        String display = textField.getText();
        int l = display.length();
        textField.remove(l-2);
        
    }//GEN-LAST:event_btn_removeActionPerformed

    public void calculate(String calc)
    {
        if(calc.equals("ADD"))
        {
             if(!(isNewField()))
            {
                int value = Integer.parseInt(textField.getText());
                setVal1(value);
                setNewField(true);
                setWaitForNew(true);
            }
            else if((isWaitForNew()))
            {
                int value = Integer.parseInt(textField.getText());
                setVal2(value);
                setResultant(getVal1() + getVal2());
                textField.setText("" + resultant);
                setVal2(0);
                setWaitForNew(false);   
            }
        }
        else if (calc.equals("SUB"))
        {
            if(!(isNewField()))
            {
                int value = Integer.parseInt(textField.getText());
                setVal1(value);
                setNewField(true);
                setWaitForNew(true);
            }
            else if((isWaitForNew()))
            {
                int value = Integer.parseInt(textField.getText());
                setVal2(value);
                setResultant(getVal1() - getVal2());
                textField.setText("" + resultant);
                setVal2(0);
                setWaitForNew(false);   
            }
        }
        else if(calc.equals("MUL"))
        {
            int value = Integer.parseInt(textField.getText());
            setResultant(resultant * value);
            setVal1(value);
            textField.setText("" + resultant);
            setNewField(true);
        }
        else if (calc.equals("DIV"))
        {
            int value = Integer.parseInt(textField.getText());
            setResultant(resultant / value);
            setVal1(value);
            textField.setText("" + resultant);
            setNewField(true);            
        }
    }
    
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        calculate("ADD");
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_equalsActionPerformed

    private void btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minusActionPerformed
        calculate("SUB");
    }//GEN-LAST:event_btn_minusActionPerformed

    private void btn_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulActionPerformed
        calculate("MUL");
    }//GEN-LAST:event_btn_mulActionPerformed

    private void btn_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divideActionPerformed
        calculate("DIV");
    }//GEN-LAST:event_btn_divideActionPerformed

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_divide;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_equals;
    private javax.swing.JButton btn_minus;
    private javax.swing.JButton btn_mul;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the one
     */
    public int getOne() {
        return one;
    }

    /**
     * @param one the one to set
     */
    public void setOne(int one) {
        this.one = one;
    }

    /**
     * @return the two
     */
    public int getTwo() {
        return two;
    }

    /**
     * @param two the two to set
     */
    public void setTwo(int two) {
        this.two = two;
    }

    /**
     * @return the three
     */
    public int getThree() {
        return three;
    }

    /**
     * @param three the three to set
     */
    public void setThree(int three) {
        this.three = three;
    }

    /**
     * @return the four
     */
    public int getFour() {
        return four;
    }

    /**
     * @param four the four to set
     */
    public void setFour(int four) {
        this.four = four;
    }

    /**
     * @return the five
     */
    public int getFive() {
        return five;
    }

    /**
     * @param five the five to set
     */
    public void setFive(int five) {
        this.five = five;
    }

    /**
     * @return the six
     */
    public int getSix() {
        return six;
    }

    /**
     * @param six the six to set
     */
    public void setSix(int six) {
        this.six = six;
    }

    /**
     * @return the seven
     */
    public int getSeven() {
        return seven;
    }

    /**
     * @param seven the seven to set
     */
    public void setSeven(int seven) {
        this.seven = seven;
    }

    /**
     * @return the eight
     */
    public int getEight() {
        return eight;
    }

    /**
     * @param eight the eight to set
     */
    public void setEight(int eight) {
        this.eight = eight;
    }

    /**
     * @return the nine
     */
    public int getNine() {
        return nine;
    }

    /**
     * @param nine the nine to set
     */
    public void setNine(int nine) {
        this.nine = nine;
    }

    /**
     * @return the zero
     */
    public int getZero() {
        return zero;
    }

    /**
     * @param zero the zero to set
     */
    public void setZero(int zero) {
        this.zero = zero;
    }

    /**
     * @return the dot
     */
    public int getDot() {
        return dot;
    }

    /**
     * @param dot the dot to set
     */
    public void setDot(char dot) {
        this.dot = dot;
    }

    /**
     * @return the btn_1
     */
    public javax.swing.JButton getBtn_1() {
        return btn_1;
    }

    /**
     * @param btn_1 the btn_1 to set
     */
    public void setBtn_1(javax.swing.JButton btn_1) {
        this.btn_1 = btn_1;
    }

    /**
     * @return the btn_2
     */
    public javax.swing.JButton getBtn_2() {
        return btn_2;
    }

    /**
     * @param btn_2 the btn_2 to set
     */
    public void setBtn_2(javax.swing.JButton btn_2) {
        this.btn_2 = btn_2;
    }

    /**
     * @return the btn_3
     */
    public javax.swing.JButton getBtn_3() {
        return btn_3;
    }

    /**
     * @param btn_3 the btn_3 to set
     */
    public void setBtn_3(javax.swing.JButton btn_3) {
        this.btn_3 = btn_3;
    }

    /**
     * @return the btn_4
     */
    public javax.swing.JButton getBtn_4() {
        return btn_4;
    }

    /**
     * @param btn_4 the btn_4 to set
     */
    public void setBtn_4(javax.swing.JButton btn_4) {
        this.btn_4 = btn_4;
    }

    /**
     * @return the btn_5
     */
    public javax.swing.JButton getBtn_5() {
        return btn_5;
    }

    /**
     * @param btn_5 the btn_5 to set
     */
    public void setBtn_5(javax.swing.JButton btn_5) {
        this.btn_5 = btn_5;
    }

    /**
     * @return the btn_6
     */
    public javax.swing.JButton getBtn_6() {
        return btn_6;
    }

    /**
     * @param btn_6 the btn_6 to set
     */
    public void setBtn_6(javax.swing.JButton btn_6) {
        this.btn_6 = btn_6;
    }

    /**
     * @return the btn_7
     */
    public javax.swing.JButton getBtn_7() {
        return btn_7;
    }

    /**
     * @param btn_7 the btn_7 to set
     */
    public void setBtn_7(javax.swing.JButton btn_7) {
        this.btn_7 = btn_7;
    }

    /**
     * @return the btn_8
     */
    public javax.swing.JButton getBtn_8() {
        return btn_8;
    }

    /**
     * @param btn_8 the btn_8 to set
     */
    public void setBtn_8(javax.swing.JButton btn_8) {
        this.btn_8 = btn_8;
    }

    /**
     * @return the btn_9
     */
    public javax.swing.JButton getBtn_9() {
        return btn_9;
    }

    /**
     * @param btn_9 the btn_9 to set
     */
    public void setBtn_9(javax.swing.JButton btn_9) {
        this.btn_9 = btn_9;
    }

    /**
     * @return the btn_add
     */
    public javax.swing.JButton getBtn_add() {
        return btn_add;
    }

    /**
     * @param btn_add the btn_add to set
     */
    public void setBtn_add(javax.swing.JButton btn_add) {
        this.btn_add = btn_add;
    }

    /**
     * @return the btn_divide
     */
    public javax.swing.JButton getBtn_divide() {
        return btn_divide;
    }

    /**
     * @param btn_divide the btn_divide to set
     */
    public void setBtn_divide(javax.swing.JButton btn_divide) {
        this.btn_divide = btn_divide;
    }

    /**
     * @return the btn_dot
     */
    public javax.swing.JButton getBtn_dot() {
        return btn_dot;
    }

    /**
     * @param btn_dot the btn_dot to set
     */
    public void setBtn_dot(javax.swing.JButton btn_dot) {
        this.btn_dot = btn_dot;
    }

    /**
     * @return the btn_equals
     */
    public javax.swing.JButton getBtn_equals() {
        return btn_equals;
    }

    /**
     * @param btn_equals the btn_equals to set
     */
    public void setBtn_equals(javax.swing.JButton btn_equals) {
        this.btn_equals = btn_equals;
    }

    /**
     * @return the btn_minus
     */
    public javax.swing.JButton getBtn_minus() {
        return btn_minus;
    }

    /**
     * @param btn_minus the btn_minus to set
     */
    public void setBtn_minus(javax.swing.JButton btn_minus) {
        this.btn_minus = btn_minus;
    }

    /**
     * @return the btn_mul
     */
    public javax.swing.JButton getBtn_mul() {
        return btn_mul;
    }

    /**
     * @param btn_mul the btn_mul to set
     */
    public void setBtn_mul(javax.swing.JButton btn_mul) {
        this.btn_mul = btn_mul;
    }

    /**
     * @return the jButton15
     */
    public javax.swing.JButton getjButton15() {
        return btn_0;
    }

    /**
     * @param jButton15 the jButton15 to set
     */
    public void setjButton15(javax.swing.JButton jButton15) {
        this.btn_0 = jButton15;
    }

    /**
     * @return the jButton17
     */
    public javax.swing.JButton getjButton17() {
        return jButton17;
    }

    /**
     * @param jButton17 the jButton17 to set
     */
    public void setjButton17(javax.swing.JButton jButton17) {
        this.jButton17 = jButton17;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }



    /**
     * @return the textField
     */
    public javax.swing.JTextField getTextField() {
        return textField;
    }

    /**
     * @param textField the textField to set
     */
    public void setTextField(javax.swing.JTextField textField) {
        this.textField = textField;
    }

    /**
     * @return the val1
     */
    public int getVal1() {
        return val1;
    }

    /**
     * @param val1 the val1 to set
     */
    public void setVal1(int val1) {
        this.val1 = val1;
    }

    /**
     * @return the val2
     */
    public int getVal2() {
        return val2;
    }

    /**
     * @param val2 the val2 to set
     */
    public void setVal2(int val2) {
        this.val2 = val2;
    }

    /**
     * @return the resultant
     */
    public int getResultant() {
        return resultant;
    }

    /**
     * @param resultant the resultant to set
     */
    public void setResultant(int resultant) {
        this.resultant = resultant;
    }

    /**
     * @return the newField
     */
    public boolean isNewField() {
        return newField;
    }

    /**
     * @param newField the newField to set
     */
    public void setNewField(boolean newField) {
        this.newField = newField;
    }

    /**
     * @return the waitForNew
     */
    public boolean isWaitForNew() {
        return waitForNew;
    }

    /**
     * @param waitForNew the waitForNew to set
     */
    public void setWaitForNew(boolean waitForNew) {
        this.waitForNew = waitForNew;
    }
}
