/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Properties;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;

/**
 *
 * @author DanishJahangir
 */
public class createEvent extends javax.swing.JFrame {

    /**
     * Creates new form createEvent
     */
    public createEvent() {
        initComponents();
        Library_File a = new Library_File();
        a.setStatusBar(statusPanel, statusLabel, this, "ems.png");
    }
    JPanel statusPanel = new JPanel();
    JLabel statusLabel = new JLabel("Ready");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_eTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_date = new com.toedter.calendar.JDateChooser();
        txt_venue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        btn_create = new javax.swing.JButton();
        cb_color = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(":: NEW EVENT ::");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 80, 30);
        getContentPane().add(txt_eTitle);
        txt_eTitle.setBounds(110, 30, 210, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Title");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 80, 30);
        getContentPane().add(txt_date);
        txt_date.setBounds(110, 70, 210, 30);

        txt_venue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_venueActionPerformed(evt);
            }
        });
        getContentPane().add(txt_venue);
        txt_venue.setBounds(110, 110, 210, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Venue");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 30);
        getContentPane().add(txt_city);
        txt_city.setBounds(110, 150, 210, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 80, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Priority Level");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 310, 80, 30);

        txt_desc.setColumns(20);
        txt_desc.setRows(5);
        jScrollPane1.setViewportView(txt_desc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 190, 210, 110);

        btn_create.setText("CREATE");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create);
        btn_create.setBounds(220, 350, 100, 30);

        cb_color.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RED", "YELLOW", "GREEN" }));
        getContentPane().add(cb_color);
        cb_color.setBounds(220, 310, 100, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 80, 30);

        setSize(new java.awt.Dimension(344, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_venueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_venueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_venueActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        statusLabel.setForeground(Color.black);
        ConnectSQLite i = new ConnectSQLite();
        String userName = i.readData("SELECT * FROM tempUser ORDER BY id DESC LIMIT 1", "user");

        index a = new index();
        if (txt_eTitle.getText().isEmpty() || txt_venue.getText().isEmpty() || txt_date.getDate() == null) {
            statusLabel.setForeground(Color.red);
            statusLabel.setText(" Error : Please fill all fields.");
            statusPanel.add(statusLabel);
        } else {
            System.out.println(a.getUserName());
            i.InsertData("Insert into tbl_event(e_title,e_date,e_venue,e_city,e_description,e_user,e_color)values('"
                    + txt_eTitle.getText() + "','" + txt_date.getDate() + "','" + txt_venue.getText() + "','"
                    + txt_city.getText() + "','" + txt_desc.getText() + "','" + userName + "','"
                    + cb_color.getSelectedItem().toString() + "')");

            statusLabel.setForeground(Color.green);
            statusLabel.setText("  Successfuly created an event.");
            statusPanel.add(statusLabel);
        }
    }//GEN-LAST:event_btn_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                Properties props = new Properties();
                props.put("logoString", "DJ Soft");
                com.jtattoo.plaf.smart.SmartLookAndFeel.setCurrentTheme(props);
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JComboBox cb_color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_city;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JTextField txt_eTitle;
    private javax.swing.JTextField txt_venue;
    // End of variables declaration//GEN-END:variables
}
