/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;

/**
 *
 * @author DanishJahangir
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        Library_File a = new Library_File();
        a.setStatusBar(statusPanel, statusLabel, this, "ems.png");
    }
    JPanel statusPanel = new JPanel();
    JLabel statusLabel = new JLabel("Ready");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_accessLevel = new javax.swing.JComboBox();
        txt_pwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: LOGIN :: ");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txt_uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_unameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_unameMouseExited(evt);
            }
        });
        txt_uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_unameKeyPressed(evt);
            }
        });
        getContentPane().add(txt_uname);
        txt_uname.setBounds(90, 170, 100, 30);

        jLabel4.setText("User Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 70, 30);

        btn_login.setText("Login");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(400, 210, 90, 30);

        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 170, 70, 30);

        cb_accessLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "accountant" }));
        cb_accessLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cb_accessLevelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cb_accessLevelMouseExited(evt);
            }
        });
        cb_accessLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_accessLevelActionPerformed(evt);
            }
        });
        getContentPane().add(cb_accessLevel);
        cb_accessLevel.setBounds(470, 170, 120, 30);

        txt_pwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_pwdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_pwdMouseExited(evt);
            }
        });
        txt_pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pwdKeyPressed(evt);
            }
        });
        getContentPane().add(txt_pwd);
        txt_pwd.setBounds(310, 170, 100, 30);

        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 210, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/01.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 930, 260);

        setSize(new java.awt.Dimension(930, 312));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_accessLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_accessLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_accessLevelActionPerformed

    public void insertUserName() {
        Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        ConnectSQLite a = new ConnectSQLite();
        a.InsertData("Insert into tempUser(user,time) values('" + txt_uname.getText() + "','" + sdf.format(cal.getTime()) + "')");

    }

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        loginCode();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_unameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_unameKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        {
            loginCode();
        }
    }//GEN-LAST:event_txt_unameKeyPressed

    private void txt_pwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwdKeyPressed
      if(evt.getKeyChar() == KeyEvent.VK_ENTER)
        {
            loginCode();
        }
    }//GEN-LAST:event_txt_pwdKeyPressed

    private void txt_unameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_unameMouseEntered
        statusLabel.setForeground(Color.black);
        statusLabel.setText(" Type in your user name here.");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_txt_unameMouseEntered

    private void txt_unameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_unameMouseExited
        statusLabel.setForeground(Color.black);
        statusLabel.setText("");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_txt_unameMouseExited

    private void txt_pwdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pwdMouseEntered
        statusLabel.setForeground(Color.black);
        statusLabel.setText(" Type in your password here.");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_txt_pwdMouseEntered

    private void txt_pwdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pwdMouseExited
        statusLabel.setForeground(Color.black);
        statusLabel.setText("");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_txt_pwdMouseExited

    private void cb_accessLevelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_accessLevelMouseEntered
        statusLabel.setText(" Set the access Level.");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_cb_accessLevelMouseEntered

    private void cb_accessLevelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_accessLevelMouseExited
        statusLabel.setForeground(Color.black);
        statusLabel.setText("");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_cb_accessLevelMouseExited

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        statusLabel.setForeground(Color.black);
        statusLabel.setText(" Get in to the world of Events.");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        statusLabel.setForeground(Color.black);
        statusLabel.setText("");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_btn_loginMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        statusLabel.setForeground(Color.black);
        statusLabel.setText(" Terminate the Program.");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        statusLabel.setForeground(Color.black);
        statusLabel.setText("");
        statusPanel.add(statusLabel);
    }//GEN-LAST:event_jButton1MouseExited

    public void loginCode()
    {
               
            String name = txt_uname.getText();
            char[] myPwd = txt_pwd.getPassword();
            String password = new String(myPwd);
            String accessLevel = cb_accessLevel.getSelectedItem().toString();
        
        statusLabel.setText("");
        statusPanel.add(statusLabel);
        if (txt_uname.getText().equalsIgnoreCase("trick") && password.equalsIgnoreCase("trick")) {
            Main sg = new Main();
            this.setVisible(false);
            sg.setVisible(true);
        } else if (txt_uname.getText().isEmpty() || password.isEmpty()) {
        statusLabel.setForeground(Color.red);
        statusLabel.setText("Please fill all fields.");
        statusPanel.add(statusLabel);
        } else {



            /*
             -----------------------------------------------
             ------- CODE FOR READING FROM DB --------------
             -----------------------------------------------
             */
            Connection connection = null;
            ResultSet resultSet = null;
            Statement statement = null;

            try {
                Class.forName("org.sqlite.JDBC");
            connection = DriverManager.getConnection("jdbc:sqlite:ems.db");
                System.out.println("Connection Successfully build !!");
                statement = connection.createStatement();
                String query = "Select e_pwd from tbl_users where e_user='" + txt_uname.getText() + "'";
                resultSet = statement.executeQuery(query);
                System.out.println("ResultSet " + resultSet.getString("e_pwd"));
                String a = resultSet.getString("e_pwd");
                if (password.equals(a)) {
                    Main sg = new Main();
                    index i = new index();

                    i.setUserName(txt_uname.getText());
                    System.out.println("" + i.getUserName());

                    try {
                        resultSet.close();
                        System.out.println("ResultSet CLOSED Success !!");
                        statement.close();
                        System.out.println("Statement CLOSED Success !!");
                        connection.close();
                        System.out.println("Connection CLOSED Success !!");
                    } catch (Exception e) {
                        System.out.println("Error : " + e.getMessage());
                    }

                    insertUserName();
                    this.setVisible(false);
                    sg.setVisible(true);
                }
                
                if(!(password.equals(a))) {
                    statusLabel.setForeground(Color.red);
                    statusLabel.setText("Invalid username or Password !!");
                    statusPanel.add(statusLabel);

                }

            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            } finally {
                try {
                    resultSet.close();
                    System.out.println("ResultSet CLOSED Success !!");
                    statement.close();
                    System.out.println("Statement CLOSED Success !!");
                    connection.close();
                    System.out.println("Connection CLOSED Success !!");
                } catch (Exception e) {
                    System.out.println("Error : " + e.getMessage());
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                Properties props = new Properties();
                props.put("logoString", "DJ Soft");
                com.jtattoo.plaf.smart.SmartLookAndFeel.setCurrentTheme(props);
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                try {
                    Thread.sleep(4000);
                } catch (Exception e) {
                }   
                
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox cb_accessLevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
